<?php

namespace AppBundle\Repository;

/**
 * cosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cosRepository extends \Doctrine\ORM\EntityRepository
{
}
