<?php
/**
 * Created by PhpStorm.
 * User: Maciek
 * Date: 2016-08-23
 * Time: 05:12
 */

namespace AppBundle\Repository;

/**
 * cosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cosRepository extends \Doctrine\ORM\EntityRepository
{
}